nuke.knobDefault('Root.fps', '25')
nuke.knobDefault("Viewer.fps", "25")
nuke.knobDefault("Root.format", "1920 1080 0 0 1920 1080 1 FullHD")
nuke.knobDefault("Read.cached", "1")
nuke.knobDefault("Read.cacheLocal", "always")
nuke.knobDefault('Card.rows', '0' );
nuke.knobDefault('Card.columns', '0' );
nuke.knobDefault('ShuffleCopy.label', '[value in] -> [value out2]\n[value in2] -> [value out]')
nuke.knobDefault('Shuffle.label', '[value in] -> [value out]')
nuke.knobDefault('Blur.label', '[value size]')
nuke.knobDefault('Blur.channels', 'alpha')
nuke.knobDefault('IBKColourV3.screen_type', 'green')
nuke.knobDefault('IBKGizmoV3.st', 'C-green')
nuke.knobDefault("CheckerBoard.centerlinewidth","0")
nuke.knobDefault("FilterErode.channels","alpha")
nuke.knobDefault("Dilate.channels","alpha")
nuke.knobDefault("Write.bookmark", "True")
nuke.knobDefault("Merge.label", "[if {[value mix]<1} { value mix }]")
nuke.knobDefault("Saturation.label", "[if {[value saturation]<1} { value saturation }]")
nuke.knobDefault("Viewer.freezeGuiWhenPlayBack", "1") 
nuke.knobDefault("Grain2.maskgrain", "False") 
nuke.knobDefault("Card2.rows", "0.0")
nuke.knobDefault("Card2.columns", "0.0")
nuke.knobDefault("Blur.size", "1.0")
nuke.knobDefault("Viewer.tile_color", "1128481791")
nuke.knobDefault("Blur.mix", "1.0")
